environment:
    global:
        branch: "feature/buckyball-cycles"
        job_name: "build-StandaloneWindows64"
        namespace: "intangiblerealities"
        project: "narupa-applications/narupa-imd"
        artifact_url: "https://gitlab.com/${namespace}/${project}/-/jobs/artifacts/${branch}/download?job=${job_name}"
        artifact_zip: "artifacts.zip"
        artifact_dir: "conda/artifacts"
        miniconda_uri: "https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe"
        miniconda: "C:\\Miniconda3"
init:
    - ps: Invoke-Webrequest -Uri ${env:miniconda_uri} -OutFile miniconda.exe
    - ps: .\miniconda.exe
    - ps: ls
    - ps: Set-Item -Path Env:Path -Value ($Env:Path + ";${env:miniconda};${env:miniconda}\Scripts")
    - ps: conda install conda-build conda-verify ripgrep 
build_script:
    - ps: Invoke-WebRequest -Uri ${env:artifact_url} -OutFile ${env:artifact_zip}
    - ps: Expand-Archive -Path ${env:artifact_zip} -DestinationPath ${env:artifact_dir}
    - ps: conda build .\conda