image: "gableroux/unity3d:2019.3.0f6-windows"

stages:
- build
- reports
- deploy

generate_report:
  stage: reports
  image: "microsoft/dotnet:latest"
  script:
    - git clone "https://gitlab.com/alexjbinnie/extentreports-dotnetcore-cli.git"
    - cd extentreports-dotnetcore-cli/ExtentReportsDotNetCLI
    - dotnet publish -c Release
    - cd ../../
    - dotnet extentreports-dotnetcore-cli/ExtentReportsDotNetCLI/ExtentReportsDotNetCLI/bin/Release/netcoreapp2.1/ExtentReportsDotNetCLI.dll -i ./editmode-results.xml
    - mv index.html editmode-results.html
  dependencies:
    test-editmode
  artifacts:
    paths:
    - $(pwd)/editmode-results.html
    when: always


# triggers an update of the Narupa unity plugin repo.
trigger_plugin_update:
  stage: deploy
  only:
    - master
  script:
    - apt-get update && apt-get install --yes curl
    - "curl -X POST -F token=${NARUPA_UNITY_PLUGIN_TOKEN} -F ref=master https://gitlab.com/api/v4/projects/14856986/trigger/pipeline"

variables:
  BUILD_NAME: Narupa iMD

.unity_before_script: &unity_before_script
  before_script:
  - chmod +x ./ci/before_script.sh && ./ci/before_script.sh

.test: &test
  stage: build
  <<: *unity_before_script
  script:
  - chmod +x ./ci/test.sh && ./ci/test.sh
  artifacts:
    paths:
    - $(pwd)/$TEST_PLATFORM-results.xml
    - $(pwd)/$TEST_PLATFORM-results.html
    when: always

test-editmode:
  <<: *test
  variables:
    TEST_PLATFORM: editmode

.build: &build
  stage: build
  <<: *unity_before_script
  script:
  - chmod +x ./ci/build.sh && ./ci/build.sh

  artifacts:
    paths:
    - ./Builds/

build-StandaloneWindows64:
  <<: *build
  variables:
    BUILD_TARGET: StandaloneWindows64
