package:
    name: narupa-imd
    version: {{ frontend_version }}

source:
    path: artifacts

build:
    number: {{ build_number }}
    missing_dso_whitelist:
        - '*\Windows\System32\*.dll'
    script_env:
      - frontend_version
      - build_number
      - NARUPA_LICENSE_PATH

app:
  entry: NarupaImd.bat
  summary: "Narupa iMD virtual reality frontend."
  type: desk

about:
  home: https://narupa.readthedocs.io
  license: GPL 3
  license_file: {{ NARUPA_LICENSE_PATH }}
  summary: Virtual reality frontend for Narupa.
  description: |
    Narupa is a framework for interactive molecular dynamics simulation in
    virtual reality. This package provides the virtual reality frontend.
  doc_url: https://narupa.readthedocs.io
  dev_url: https://gitlab.com/intangiblerealities/narupa-applications/narupa-imd
