package:
    name: nanover-imd
    version: {{ frontend_version }}

source:
    path: artifacts

build:
    number: {{ build_number }}
    missing_dso_whitelist:
        - '*\Windows\System32\*.dll'
    script_env:
      - frontend_version
      - build_number
      - NARUPA_LICENSE_PATH

app:
  entry: NanoverImd.bat
  summary: "Nanover iMD virtual reality frontend."
  type: desk

about:
  home: https://nanover.readthedocs.io
  license: MIT
  license_file: {{ NARUPA_LICENSE_PATH }}
  summary: Virtual reality frontend for NanoVer.
  description: |
    NanoVer is a framework for interactive molecular dynamics simulation in
    virtual reality. This package provides the virtual reality frontend.
  doc_url: https://nanover.readthedocs.io
  dev_url: https://gitlab.com/intangiblerealities/nanover-applications/nanover-imd
